sudo: false
language: php
php:
<<<<<<< HEAD
  - nightly
  - 5.6
  - 5.5
  - 5.4
  - hhvm

matrix:
=======
  - 7.0
  - 5.6
  - 5.5
  - nightly

matrix:
  fast_finish: true
>>>>>>> 44b515d1f343df3e0a1bb74cf04ca9508716fe4a
  allow_failures:
    - php: nightly

cache:
<<<<<<< HEAD
  directories:
    - bower_components
    - node_modules

install:
  - npm install -g npm@latest
  - npm install -g bower gulp jscs
  - npm install
  - composer self-update && composer --version
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - composer global require squizlabs/php_codesniffer

script:
  - npm run build
  - npm run jshint
  - npm run jscs
  - phpcs --standard=ruleset.xml --extensions=php -n -s .
=======
  apt: true
  directories:
    - $HOME/.composer/cache
    - vendor

before_install:
  - phpenv config-rm xdebug.ini
  - composer self-update

install:
  - composer install -o --prefer-dist --no-interaction

script:
  - composer test
>>>>>>> 44b515d1f343df3e0a1bb74cf04ca9508716fe4a
